version: '2.1'

services:
        users-service:
                container_name: users-service
                build: .
                volumes:
                        - '.:/usr/src/app'
                ports:
                        - 5001:5000
                environment:
                        - APP_SETTINGS=app.config.DevelopmentConfig
                        - DATABASE_DEV_URL=mysql+pymysql://root:123456@192.168.50.78:3306/users_dev
                        - DATABASE_TEST_URL=mysql+pymysql://root:123456@192.168.50.78:3306/users_test