version: '2.1'

services:
        users-service:
                container_name: users-service
                build: .
                expose:
                  - '5000'
                environment:
                        - APP_SETTINGS=app.config.ProjectConfig
                        - DATABASE_TEST_URL=mysql+pymysql://root:123456@192.168.50.78:3306/users_test
                        - DATABASE_PROJECT_URL=mysql+pymysql://root:123456@192.168.50.78:3306/users_prod
                command: gunicorn -b 0.0.0.0:5000 manage:app
        nginx:
          container_name: nginx
          build: ./nginx/
          restart: always
          ports:
            - 80:80
          depends_on:
            users-service:
              condition: service_started
          links:
            - users-service